services:
  postgres:
    image: postgres
    container_name: pcp-postgres
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d/  # Mount directory for initialization scripts
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
    ports:
      - 5432:5432
  redis:
    image: redis
    container_name: pcp-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  postgresql:
  postgresql_data:
  redis-data:
